version: '3'

services:
  domain:
    build: ./
    command: ./wait-for-postgres.sh db ./main
    depends_on:
      - db
    ports:
      - 9080:9080
    environment:
      - DB_PASSWORD=12345
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=portDb
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./cmd/database/db/migrations/000001_create_users_table.up.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./cmd/database/db/fill_table.sql:/docker-entrypoint-initdb.d/fill_tables.sql


  client:
    build: ../PortMicroserviceClient/
    command: ./main
    ports:
      - 3000:3000
    depends_on:
      - domain

volumes:
  postgres:
