// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: api/proto/port.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPortsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetPortsRequest) Reset() {
	*x = GetPortsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_port_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortsRequest) ProtoMessage() {}

func (x *GetPortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_port_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortsRequest.ProtoReflect.Descriptor instead.
func (*GetPortsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_port_proto_rawDescGZIP(), []int{0}
}

func (x *GetPortsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPortsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List string `protobuf:"bytes,1,opt,name=List,proto3" json:"List,omitempty"`
}

func (x *GetPortsResponse) Reset() {
	*x = GetPortsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_port_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortsResponse) ProtoMessage() {}

func (x *GetPortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_port_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortsResponse.ProtoReflect.Descriptor instead.
func (*GetPortsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_port_proto_rawDescGZIP(), []int{1}
}

func (x *GetPortsResponse) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type UpsertPortsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *UpsertPortsRequest) Reset() {
	*x = UpsertPortsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_port_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertPortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPortsRequest) ProtoMessage() {}

func (x *UpsertPortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_port_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPortsRequest.ProtoReflect.Descriptor instead.
func (*UpsertPortsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_port_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertPortsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpsertPortsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List string `protobuf:"bytes,1,opt,name=List,proto3" json:"List,omitempty"`
}

func (x *UpsertPortsResponse) Reset() {
	*x = UpsertPortsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_port_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertPortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPortsResponse) ProtoMessage() {}

func (x *UpsertPortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_port_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPortsResponse.ProtoReflect.Descriptor instead.
func (*UpsertPortsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_port_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertPortsResponse) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

var File_api_proto_port_proto protoreflect.FileDescriptor

var file_api_proto_port_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x25, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x12, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6f,
	0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x32,
	0x81, 0x01, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x37, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50,
	0x6f, 0x72, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x40, 0x0a, 0x0b, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x73,
	0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6f, 0x72,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_port_proto_rawDescOnce sync.Once
	file_api_proto_port_proto_rawDescData = file_api_proto_port_proto_rawDesc
)

func file_api_proto_port_proto_rawDescGZIP() []byte {
	file_api_proto_port_proto_rawDescOnce.Do(func() {
		file_api_proto_port_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_port_proto_rawDescData)
	})
	return file_api_proto_port_proto_rawDescData
}

var file_api_proto_port_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_port_proto_goTypes = []interface{}{
	(*GetPortsRequest)(nil),     // 0: api.GetPortsRequest
	(*GetPortsResponse)(nil),    // 1: api.GetPortsResponse
	(*UpsertPortsRequest)(nil),  // 2: api.UpsertPortsRequest
	(*UpsertPortsResponse)(nil), // 3: api.UpsertPortsResponse
}
var file_api_proto_port_proto_depIdxs = []int32{
	0, // 0: api.Port.GetPorts:input_type -> api.GetPortsRequest
	2, // 1: api.Port.UpsertPorts:input_type -> api.UpsertPortsRequest
	1, // 2: api.Port.GetPorts:output_type -> api.GetPortsResponse
	3, // 3: api.Port.UpsertPorts:output_type -> api.UpsertPortsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_port_proto_init() }
func file_api_proto_port_proto_init() {
	if File_api_proto_port_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_port_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPortsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_port_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPortsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_port_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertPortsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_port_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertPortsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_port_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_port_proto_goTypes,
		DependencyIndexes: file_api_proto_port_proto_depIdxs,
		MessageInfos:      file_api_proto_port_proto_msgTypes,
	}.Build()
	File_api_proto_port_proto = out.File
	file_api_proto_port_proto_rawDesc = nil
	file_api_proto_port_proto_goTypes = nil
	file_api_proto_port_proto_depIdxs = nil
}
