// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PortClient is the client API for Port service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortClient interface {
	GetPorts(ctx context.Context, in *GetPortsRequest, opts ...grpc.CallOption) (*GetPortsResponse, error)
	UpsertPorts(ctx context.Context, in *UpsertPortsRequest, opts ...grpc.CallOption) (*UpsertPortsResponse, error)
}

type portClient struct {
	cc grpc.ClientConnInterface
}

func NewPortClient(cc grpc.ClientConnInterface) PortClient {
	return &portClient{cc}
}

func (c *portClient) GetPorts(ctx context.Context, in *GetPortsRequest, opts ...grpc.CallOption) (*GetPortsResponse, error) {
	out := new(GetPortsResponse)
	err := c.cc.Invoke(ctx, "/api.Port/GetPorts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portClient) UpsertPorts(ctx context.Context, in *UpsertPortsRequest, opts ...grpc.CallOption) (*UpsertPortsResponse, error) {
	out := new(UpsertPortsResponse)
	err := c.cc.Invoke(ctx, "/api.Port/UpsertPorts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortServer is the server API for Port service.
// All implementations must embed UnimplementedPortServer
// for forward compatibility
type PortServer interface {
	GetPorts(context.Context, *GetPortsRequest) (*GetPortsResponse, error)
	UpsertPorts(context.Context, *UpsertPortsRequest) (*UpsertPortsResponse, error)
	mustEmbedUnimplementedPortServer()
}

// UnimplementedPortServer must be embedded to have forward compatible implementations.
type UnimplementedPortServer struct {
}

func (UnimplementedPortServer) GetPorts(context.Context, *GetPortsRequest) (*GetPortsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPorts not implemented")
}
func (UnimplementedPortServer) UpsertPorts(context.Context, *UpsertPortsRequest) (*UpsertPortsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertPorts not implemented")
}
func (UnimplementedPortServer) mustEmbedUnimplementedPortServer() {}

// UnsafePortServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortServer will
// result in compilation errors.
type UnsafePortServer interface {
	mustEmbedUnimplementedPortServer()
}

func RegisterPortServer(s grpc.ServiceRegistrar, srv PortServer) {
	s.RegisterService(&Port_ServiceDesc, srv)
}

func _Port_GetPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServer).GetPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Port/GetPorts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServer).GetPorts(ctx, req.(*GetPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Port_UpsertPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServer).UpsertPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Port/UpsertPorts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServer).UpsertPorts(ctx, req.(*UpsertPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Port_ServiceDesc is the grpc.ServiceDesc for Port service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Port_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Port",
	HandlerType: (*PortServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPorts",
			Handler:    _Port_GetPorts_Handler,
		},
		{
			MethodName: "UpsertPorts",
			Handler:    _Port_UpsertPorts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/port.proto",
}
